In [1]:
import numpy as np

In [2]:
list1 = ['a', 1, True]
for i in list1:
    print(type(i))

<class 'str'>
<class 'int'>
<class 'bool'>


In [3]:
# only store one type of data
arr = np.array([1,'a',True])
for i in arr:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
# 1-dimensional array or vector
arr1 = np.array([1,2,3,4])
# 2-dimensional array or matrix
arr2 = np.array([[1,2,3,4], [5,6,7,8]])

In [5]:
arr1[0]

1

In [6]:
arr2[-1]

array([5, 6, 7, 8])

In [7]:
arr2.shape

(2, 4)

In [8]:
arr2.dtype

dtype('int32')

In [9]:
arr4 = np.array([1,2,3], dtype='str')
arr4

array(['1', '2', '3'], dtype='<U1')

In [10]:
arr5 = np.zeros(5)
arr5

array([0., 0., 0., 0., 0.])

In [11]:
arr6 = np.ones(6)
arr6

array([1., 1., 1., 1., 1., 1.])

In [12]:
arr7 = np.empty(7)
arr7

array([2.41907520e-312, 2.14321575e-312, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.78022341e-306, 2.33423131e-312])

In [13]:
arr8 = np.arange(8)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
np.sort([3,7,9,1,4])

array([1, 3, 4, 7, 9])

In [15]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
np.concatenate((arr_a, arr_b))

array([1, 2, 3, 4, 5, 6])

In [16]:
arr_c = np.array([[1,2,3], [4,5,6]])
arr_d = np.array([[4,5,6], [7,8,9]])
np.concatenate((arr_c, arr_d), axis=1)

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

In [17]:
np.concatenate((arr_c, arr_d), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr_9 = np.array([[[1,2,3], [4,5,6]], [[2,3,4], [5,6,7]], [[1,6,9], [6,8,9]]])
arr_9

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 3, 4],
        [5, 6, 7]],

       [[1, 6, 9],
        [6, 8, 9]]])

In [19]:
arr_9.ndim # returns no. of dimensions

3

In [20]:
arr_9.shape # 3 lists contains 2 list that contains 3 elements

(3, 2, 3)

In [21]:
arr10 = np.array([1,2,3,4,5,6])
arr10.reshape(2,3) # 2 lists of 3 elements

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr10.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])