In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
arr.shape

(6,)

In [3]:
arr2 = arr[np.newaxis, :] # add new axis as row
arr2

array([[1, 2, 3, 4, 5, 6]])

In [4]:
arr2.shape

(1, 6)

In [5]:
arr3 = arr[:, np.newaxis] # add new axis as column
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [6]:
arr3.shape

(6, 1)

In [7]:
arr4 = np.expand_dims(arr, axis=1)
arr4

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [8]:
arr[arr>3]

array([4, 5, 6])

In [9]:
num = arr[arr%2==0]
num

array([2, 4, 6])

In [10]:
arr1 = [[1,2], [2,2]]
arr2 = [[2,2], [3,2]]
np.vstack((arr1, arr2))

array([[1, 2],
       [2, 2],
       [2, 2],
       [3, 2]])

In [11]:
np.hstack((arr1, arr2))

array([[1, 2, 2, 2],
       [2, 2, 3, 2]])

In [12]:
arr5 = np.arange(1,13).reshape(2,6)
arr5

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [13]:
np.hsplit(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [14]:
original = np.arange(10)
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
new_arr = original[3:6]
new_arr

array([3, 4, 5])

In [16]:
new_arr[0] = 99
new_arr

array([99,  4,  5])

In [17]:
original # created shallow copy modofoed original array

array([ 0,  1,  2, 99,  4,  5,  6,  7,  8,  9])

In [18]:
# deep copy
new_arr2 = original.copy()
new_arr2

array([ 0,  1,  2, 99,  4,  5,  6,  7,  8,  9])

In [19]:
new_arr2[0] = 99
new_arr2

array([99,  1,  2, 99,  4,  5,  6,  7,  8,  9])

In [20]:
original

array([ 0,  1,  2, 99,  4,  5,  6,  7,  8,  9])

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])

arr1 + arr2 # element wise operation

array([2, 4, 6])

In [22]:
arr1 - arr2

array([0, 0, 0])

In [23]:
arr1.sum()

6

In [24]:
arr1 * 2

array([2, 4, 6])