In [1]:
import numpy as np

In [2]:
# matrices, 2D - array
arr = np.array([[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
arr[2][0] # last list, first index

5

In [4]:
# random numbers
arr1 = np.random.default_rng()
arr1

Generator(PCG64) at 0x1999B555E00

In [5]:
arr1.integers(low=1, high=5, size=(3,4))

array([[3, 3, 2, 3],
       [1, 1, 4, 4],
       [4, 4, 2, 3]], dtype=int64)

In [6]:
arr1.random(size=(2,3))

array([[0.75204365, 0.62423838, 0.15928744],
       [0.27333747, 0.7718836 , 0.62650876]])

In [7]:
# find unique elements
arr2 = np.array([1,2,3,4,5,6,1,2])
np.unique(arr)

array([1, 2, 3, 4, 5, 6])

In [8]:
np.unique(arr, return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5], dtype=int64),
 array([1, 1, 1, 1, 1, 1], dtype=int64))

In [9]:
# transpose
arr.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [10]:
arr.T

array([[1, 3, 5],
       [2, 4, 6]])

In [11]:
# reversing arrays
np.flip(arr2)

array([2, 1, 6, 5, 4, 3, 2, 1])

In [12]:
np.flip(arr)

array([[6, 5],
       [4, 3],
       [2, 1]])

In [13]:
np.flip(arr, axis=1)

array([[2, 1],
       [4, 3],
       [6, 5]])

In [14]:
# flattening multi-dimensional array
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [15]:
arr.ravel() # deep copy

array([1, 2, 3, 4, 5, 6])

In [16]:
# saving and loading numpy obj as binary file
np.save('array.npy', arr) # np.save store single ndarray obj, np.savez for multi
np.load('array.npy')

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
# savetxt, loadtxt for .txt